---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Поддержка переключения языков (русский, английский)
  - Содержание на сайте должно быть на двух языках
  - Контент на сайте должен быть грамматически корректным
  - Пользователь должен иметь возможность зарегестрироваться или выполнить вход в уже существующий аккаунт
  - Пользователь должен иметь возможность просмотра списка заказов
  - Пользователь должен иметь возможность просмотра информации о заказе
  - Пользователь должен иметь возможность оставлять собственные или просматривать уже существующие отзывы
  - Сайт должен соответсвовать требованиям закона о персональных данных
